Author:      Charles H. Pence  
Description: This is a test of a key with a value  
             that goes on for lots and lots of  
             different lines and whatnot.  
Date:        October 8, 2012  
Other:       This file is all metadata, but has no tags  